[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[params.variables]
black = "#000"
body_color = "#FFF"
border_color = "#E1E1E1"
color_primary = "#F0BF65"
font_icon = "Font Awesome 6 Free"
font_primary = "Raleway:wght@400"
font_primary_type = "sans-serif"
font_scale = "1.3"
font_secondary = "Merriweather Sans:wght@400;700"
font_secondary_type = "sans-serif"
font_size = "15px"
light = "#f2f2f2"
text_color = "#555"
text_dark = "#222"
text_light = "#999"
white = "#FFF"
