############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 4


  [[main]]
  name = "Categories"
  url = "categories/"
  weight = 2

  [[main]]
name = "Join Forum"
url = "https://t.me/Thecyberswat"
weight = 3

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
