about_widget_content = "Lorem ipsum dolor sit amet, conse tfctetur adipiscing elit. Vel in in donec iaculis tempasus odio nunc laoreet . Libero ullam rgscorper."
address = "Jakarta City"
author = "Weclystack"
categories_title = "Blog Categories"
contact_form_action = "https://formspree.io/f/xwkjlnwk"
copyright = "Copyright 2023"
custom_script = ""
description = "This is meta description"
email = "info@programplex.dev"
error_404_button = "Back To Home"
error_404_text = "404 Page Not Found!"
favicon = "images/favicon.png"
featured_post_button = "Trend Topics"
featured_post_title = "Trend Topics"
footer_content = "Programplex is a platform for Programmers and Cyber Security experts, which can be joined by anyone interested in the field. So it is a platform for community or online resources for programmers, developers and cyber security experts."
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Programplex"
logo_width = "70x"
mainSections = ["blog"]
navbar_fixed = false
next_button = "Next"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"
posts_title = "Featured"
previous_button = "Previous"
read_more_button = "Read more"
recent_post_button = "New Post"
recent_post_title = "What's new?"
related_posts = "Related Posts"
search = true
showing_posts = "Showing Post From"
theme_copyright = true
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "About Programplex"
button_link = "about/"
content = "Programplex is a platform for Programmers and Cyber ​​Security Experts."
enable = true
image = "images/banner.png"
title_large = "Welcome **👋**"
title_small = "To Programplex"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = true
expire_days = 2
[preloader]
enable = false
preloader = ""
[widgets]
sidebar = ["categories", "recent-post"]
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/programplex"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/programplex"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/programplex/"
title = "instagram"
