about_widget_content = "Thecyberswat About"
address = "Jakarta City"
author = "Writed By Claysec"
categories_title = "Blog Categories"
contact_form_action = "https://formspree.io/f/xwkjlnwk"
copyright = "Copyright 2023"
custom_script = ""
description = "Thecyberswat"
email = "heyy@thecyberswat.com"
error_404_button = "Back To Home"
error_404_text = "Ups Salah jalur Broo!"
favicon = "images/favicon.png"
featured_post_button = "Trend Topics"
featured_post_title = "Trend Topics"
footer_content = "Thecyberswat is a platform for Cyber Security and Programmers experts, which can be joined by anyone interested in the field. So it is a platform for community or online resources for programmers, developers and cyber security experts."
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Thecyberswat"
logo_width = "180x"
mainSections = ["blog"]
navbar_fixed = false
next_button = "Next"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"
posts_title = "Featured"
previous_button = "Previous"
read_more_button = "Read more"
recent_post_button = "New Post"
recent_post_title = "What's new?"
related_posts = "Related Posts"
search = true
showing_posts = "Showing Post From"
theme_copyright = true
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "About Us"
button_link = "about/"
content = "Thecyberswat is a platform for Cyber Security and Pentester Experts."
enable = true
image = "images/banner.png"
title_large = "Learn Cybersec"
title_small = "From Zero to hero"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = true
expire_days = "2"
[preloader]
enable = false
preloader = ""
[widgets]
sidebar = ["categories", "recent-post"]
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/thecyberswat"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/thecyberswat"
title = "instagram"
